create table chukous
(
    chukou_id   int auto_increment
        primary key,
    station_id  int          not null,
    chukou_name varchar(255) not null,
    constraint chukou_name
        unique (chukou_name),
    constraint chukous_ibfk_1
        foreign key (station_id) references stations (station_id)
);

create index station_id
    on chukous (station_id);

INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (1, 1, 'Hanling_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (2, 1, 'Hanling_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (3, 1, 'Hanling_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (4, 2, 'Shangfen_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (5, 2, 'Shangfen_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (6, 3, '  Longcheng Park_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (7, 3, '  Longcheng Park_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (8, 3, '  Longcheng Park_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (9, 3, '  Longcheng Park_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (10, 4, 'Yanzihu_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (11, 4, 'Yanzihu_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (12, 4, 'Yanzihu_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (13, 4, 'Yanzihu_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (14, 5, 'Buxin_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (15, 5, 'Buxin_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (16, 6, 'Qianwan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (17, 7, 'Bantian_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (18, 7, 'Bantian_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (19, 7, 'Bantian_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (20, 7, 'Bantian_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (21, 8, 'Hi-tech South_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (22, 8, 'Hi-tech South_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (23, 8, 'Hi-tech South_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (24, 9, 'Longyuan Station_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (25, 9, 'Longyuan Station_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (26, 9, 'Longyuan Station_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (27, 10, 'Luohu_B出口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (28, 10, 'Luohu_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (29, 11, 'Gangxia North_1号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (30, 11, 'Gangxia North_7号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (31, 11, 'Gangxia North_12号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (32, 11, 'Gangxia North_19号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (33, 11, 'Gangxia North_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (34, 12, 'Guanlan_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (35, 13, 'Xili_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (36, 13, 'Xili_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (37, 13, 'Xili_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (38, 13, 'Xili_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (39, 13, 'Xili_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (40, 13, 'Xili_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (41, 14, 'Xiangxicun_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (42, 14, 'Xiangxicun_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (43, 14, 'Xiangxicun_D1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (44, 14, 'Xiangxicun_D2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (45, 15, 'Laojie_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (46, 15, 'Laojie_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (47, 15, 'Laojie_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (48, 15, 'Laojie_G出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (49, 16, 'Antuo Hill_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (50, 17, 'Shangtang_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (51, 18, 'Niuhu_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (52, 19, 'Minzhi_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (53, 19, 'Minzhi_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (54, 19, 'Minzhi_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (55, 20, 'Xiaomeisha_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (56, 21, 'Hongling South_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (57, 21, 'Hongling South_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (58, 21, 'Hongling South_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (59, 22, 'Nankeng_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (60, 22, 'Nankeng_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (61, 22, 'Nankeng_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (62, 23, 'Hi-Tech Park_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (63, 23, 'Hi-Tech Park_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (64, 23, 'Hi-Tech Park_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (65, 24, 'Pingshan Center_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (66, 24, 'Pingshan Center_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (67, 25, 'Mumianwan_B1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (68, 25, 'Mumianwan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (69, 25, 'Mumianwan_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (70, 26, 'Huanggangcun_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (71, 27, 'Shenwan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (72, 27, 'Shenwan_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (73, 28, 'Ma\'an Hill_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (74, 28, 'Ma\'an Hill_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (75, 28, 'Ma\'an Hill_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (76, 28, 'Ma\'an Hill_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (77, 29, 'Yitian_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (78, 29, 'Yitian_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (79, 30, 'Taoyuan_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (80, 30, 'Taoyuan_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (81, 31, 'Lianhua West_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (82, 31, 'Lianhua West_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (83, 32, 'Yangtai Mountain East_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (84, 32, 'Yangtai Mountain East_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (85, 32, 'Yangtai Mountain East_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (86, 32, 'Yangtai Mountain East_C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (87, 33, 'Shangwu_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (88, 33, 'Shangwu_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (89, 34, 'Songgang Park_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (90, 35, 'Songgang_G出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (91, 35, 'Songgang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (92, 35, 'Songgang_A口出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (93, 35, 'Songgang_E口出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (94, 36, 'Nanshan Book Mall_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (95, 36, 'Nanshan Book Mall_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (96, 37, 'Guomao_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (97, 37, 'Guomao_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (98, 37, 'Guomao_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (99, 37, 'Guomao_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (100, 38, 'Chaguang_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (101, 38, 'Chaguang_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (102, 38, 'Chaguang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (103, 38, 'Chaguang_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (104, 39, 'Yuehaimen_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (105, 39, 'Yuehaimen_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (106, 39, 'Yuehaimen_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (107, 40, 'Shenzhen World North_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (108, 40, 'Shenzhen World North_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (109, 41, 'Sea World_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (110, 41, 'Sea World_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (111, 41, 'Sea World_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (112, 41, 'Sea World_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (113, 42, 'Gushu_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (114, 42, 'Gushu_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (115, 42, 'Gushu_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (116, 42, 'Gushu_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (117, 43, 'Wanxia_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (118, 43, 'Wanxia_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (119, 44, 'Shenzhen University South_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (120, 44, 'Shenzhen University South_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (121, 45, 'Guangyayuan_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (122, 45, 'Guangyayuan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (123, 46, 'Xintangwei Station_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (124, 46, 'Xintangwei Station_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (125, 46, 'Xintangwei Station_C出人口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (126, 46, 'Xintangwei Station_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (127, 47, 'Xixiang_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (128, 47, 'Xixiang_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (129, 48, 'Tianbei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (130, 48, 'Tianbei_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (131, 48, 'Tianbei_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (132, 48, 'Tianbei_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (133, 48, 'Tianbei_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (134, 49, 'Huawei_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (135, 49, 'Huawei_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (136, 50, 'Pinghu_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (137, 50, 'Pinghu_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (138, 51, 'Dongjiang Column Memorial 
Hall Station_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (139, 51, 'Dongjiang Column Memorial 
Hall Station_坪山人民医院：M479,818,939路B线,M143,M546路外环,939路A线,M546路内环,964路B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (140, 51, 'Dongjiang Column Memorial 
Hall Station_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (141, 52, 'OCT_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (142, 52, 'OCT_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (143, 53, 'Minle_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (144, 54, 'Bao\'an_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (145, 55, 'Nanguang_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (146, 56, 'Aobei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (147, 56, 'Aobei_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (148, 56, 'Aobei_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (149, 57, 'Haiyue_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (150, 57, 'Haiyue_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (151, 57, 'Haiyue_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (152, 58, 'Donggualing_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (153, 58, 'Donggualing_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (154, 58, 'Donggualing_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (155, 59, 'Shangjing Station_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (156, 59, 'Shangjing Station_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (157, 59, 'Shangjing Station_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (158, 59, 'Shangjing Station_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (159, 60, 'Futian_1号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (160, 60, 'Futian_3号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (161, 60, 'Futian_13号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (162, 61, 'Danzhutou_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (163, 61, 'Danzhutou_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (164, 61, 'Danzhutou_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (165, 62, 'Zhucun_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (166, 63, 'Menghai_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (167, 63, 'Menghai_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (168, 64, 'Futian Bonded Area_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (169, 65, 'Dengliang_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (170, 65, 'Dengliang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (171, 65, 'Dengliang_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (172, 65, 'Dengliang_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (173, 66, 'Children\'s Palace_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (174, 67, 'Zhuguang_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (175, 67, 'Zhuguang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (176, 67, 'Zhuguang_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (177, 68, 'Universiade Center_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (178, 68, 'Universiade Center_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (179, 68, 'Universiade Center_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (180, 68, 'Universiade Center_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (181, 68, 'Universiade Center_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (182, 68, 'Universiade Center_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (183, 69, 'Convention & Exhibition City_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (184, 70, 'Pingzhou_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (185, 71, 'Haishan_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (186, 71, 'Haishan_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (187, 71, 'Haishan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (188, 71, 'Haishan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (189, 72, 'Nigang_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (190, 72, 'Nigang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (191, 73, 'Jinlong_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (192, 73, 'Jinlong_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (193, 74, 'Science Park_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (194, 75, 'Huaqiang North_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (195, 75, 'Huaqiang North_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (196, 75, 'Huaqiang North_E1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (197, 75, 'Huaqiang North_E2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (198, 76, 'Xianhu Rd_');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (199, 77, 'Shuibei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (200, 78, 'Mawan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (201, 78, 'Mawan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (202, 79, 'Heshuikou_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (203, 80, 'Liuhe station_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (204, 81, 'Xiangmei North_B2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (205, 82, 'Yuanfen_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (206, 82, 'Yuanfen_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (207, 83, 'Chiwei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (208, 83, 'Chiwei_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (209, 83, 'Chiwei_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (210, 83, 'Chiwei_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (211, 84, 'Meijing_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (212, 84, 'Meijing_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (213, 84, 'Meijing_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (214, 84, 'Meijing_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (215, 85, 'Yabao_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (216, 86, 'Bantian North_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (217, 86, 'Bantian North_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (218, 87, 'Pingluan Hill_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (219, 87, 'Pingluan Hill_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (220, 88, 'Tanglang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (221, 88, 'Tanglang_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (222, 89, 'Shaibu_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (223, 89, 'Shaibu_A3出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (224, 89, 'Shaibu_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (225, 89, 'Shaibu_D1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (226, 89, 'Shaibu_D3出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (227, 90, 'Xikeng_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (228, 91, 'Loucun_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (229, 92, 'Yantianxu_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (230, 92, 'Yantianxu_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (231, 92, 'Yantianxu_盐田海鲜街：B925C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (232, 93, 'Kengzi_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (233, 93, 'Kengzi_龙田路口：366、E34、M361                                                   B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (234, 93, 'Kengzi_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (235, 93, 'Kengzi_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (236, 94, 'Dongjiaotou_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (237, 94, 'Dongjiaotou_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (238, 95, 'Yannan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (239, 95, 'Yannan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (240, 95, 'Yannan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (241, 96, 'Huangmugang_1号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (242, 96, 'Huangmugang_3号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (243, 96, 'Huangmugang_13号口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (244, 97, 'Qiaotou_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (245, 97, 'Qiaotou_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (246, 97, 'Qiaotou_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (247, 97, 'Qiaotou_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (248, 98, 'Baotian 1st Road_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (249, 98, 'Baotian 1st Road_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (250, 98, 'Baotian 1st Road_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (251, 99, 'Shiyaling_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (252, 99, 'Shiyaling_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (253, 99, 'Shiyaling_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (254, 99, 'Shiyaling_J出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (255, 99, 'Shiyaling_K出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (256, 100, 'Liyumen_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (257, 101, 'Huaxin_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (258, 101, 'Huaxin_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (259, 101, 'Huaxin_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (260, 101, 'Huaxin_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (261, 101, 'Huaxin_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (262, 101, 'Huaxin_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (263, 102, 'Gongming Square_');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (264, 103, 'Pingshan wei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (265, 103, 'Pingshan wei_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (266, 103, 'Pingshan wei_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (267, 104, 'Bao\'an Stadium_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (268, 104, 'Bao\'an Stadium_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (269, 104, 'Bao\'an Stadium_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (270, 105, 'Qinghu North_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (271, 106, 'Shutianpu_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (272, 106, 'Shutianpu_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (273, 106, 'Shutianpu_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (274, 106, 'Shutianpu_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (275, 107, 'Gangtou_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (276, 107, 'Gangtou_C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (277, 107, 'Gangtou_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (278, 107, 'Gangtou_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (279, 108, 'Liantang Checkpoint_A3出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (280, 108, 'Liantang Checkpoint_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (281, 108, 'Liantang Checkpoint_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (282, 108, 'Liantang Checkpoint_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (283, 109, 'Fanshen_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (284, 109, 'Fanshen_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (285, 109, 'Fanshen_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (286, 110, 'Yinhu_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (287, 111, 'Shenwai Senior Campus_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (288, 112, 'Shuanglong Station_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (289, 112, 'Shuanglong Station_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (290, 112, 'Shuanglong Station_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (291, 112, 'Shuanglong Station_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (292, 113, 'Nonglin_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (293, 113, 'Nonglin_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (294, 113, 'Nonglin_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (295, 114, 'Changlong_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (296, 114, 'Changlong_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (297, 114, 'Changlong_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (298, 115, 'Honghuashan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (299, 115, 'Honghuashan_B1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (300, 115, 'Honghuashan_B2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (301, 115, 'Honghuashan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (302, 115, 'Honghuashan_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (303, 115, 'Honghuashan_E1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (304, 115, 'Honghuashan_E2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (305, 116, 'Sungang_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (306, 116, 'Sungang_C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (307, 116, 'Sungang_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (308, 117, 'Xixiang Taoyuan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (309, 117, 'Xixiang Taoyuan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (310, 117, 'Xixiang Taoyuan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (311, 118, 'Qiaotou West_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (312, 119, 'Silian_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (313, 119, 'Silian_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (314, 119, 'Silian_E1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (315, 119, 'Silian_E2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (316, 120, 'Huaqiang Rd_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (317, 120, 'Huaqiang Rd_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (318, 120, 'Huaqiang Rd_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (319, 120, 'Huaqiang Rd_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (320, 121, 'Songyuanxia_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (321, 122, 'Yangmei_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (322, 122, 'Yangmei_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (323, 123, 'Tai\'an_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (324, 123, 'Tai\'an_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (325, 124, 'Fuhai West_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (326, 125, 'Luohu  North_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (327, 126, 'Shixia_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (328, 126, 'Shixia_G出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (329, 127, 'Bei\'er Rd_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (330, 127, 'Bei\'er Rd_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (331, 127, 'Bei\'er Rd_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (332, 127, 'Bei\'er Rd_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (333, 128, 'Liangmao Hill_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (334, 129, 'Shajing_B1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (335, 129, 'Shajing_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (336, 129, 'Shajing_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (337, 130, 'Shekou Port_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (338, 130, 'Shekou Port_D1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (339, 131, 'Futian Checkpoint_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (340, 131, 'Futian Checkpoint_D1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (341, 131, 'Futian Checkpoint_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (342, 131, 'Futian Checkpoint_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (343, 132, 'Guantian_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (344, 132, 'Guantian_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (345, 133, 'Pinghuan_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (346, 134, 'Caopu_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (347, 134, 'Caopu_D2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (348, 135, 'Xin\'an_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (349, 135, 'Xin\'an_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (350, 135, 'Xin\'an_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (351, 135, 'Xin\'an_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (352, 136, 'Litchi Orchards_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (353, 136, 'Litchi Orchards_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (354, 136, 'Litchi Orchards_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (355, 136, 'Litchi Orchards_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (356, 136, 'Litchi Orchards_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (357, 137, 'Ludancun_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (358, 137, 'Ludancun_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (359, 137, 'Ludancun_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (360, 138, 'Huanancheng_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (361, 138, 'Huanancheng_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (362, 139, 'Bitou_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (363, 139, 'Bitou_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (364, 140, 'Shangchuan_B1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (365, 140, 'Shangchuan_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (366, 140, 'Shangchuan_J出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (367, 141, 'Shopping Park_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (368, 141, 'Shopping Park_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (369, 141, 'Shopping Park_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (370, 141, 'Shopping Park_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (371, 141, 'Shopping Park_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (372, 142, 'Jixiang_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (373, 142, 'Jixiang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (374, 142, 'Jixiang_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (375, 143, 'Shenyun_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (376, 143, 'Shenyun_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (377, 144, 'Shawei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (378, 144, 'Shawei_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (379, 144, 'Shawei_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (380, 144, 'Shawei_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (381, 145, 'Bihaiwan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (382, 145, 'Bihaiwan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (383, 145, 'Bihaiwan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (384, 145, 'Bihaiwan_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (385, 146, 'Airport North_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (386, 147, 'Huilongpu  station
_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (387, 148, 'Hourui_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (388, 148, 'Hourui_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (389, 149, 'Liuyue_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (390, 149, 'Liuyue_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (391, 150, 'Xingdong_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (392, 150, 'Xingdong_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (393, 150, 'Xingdong_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (394, 150, 'Xingdong_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (395, 151, 'Huaide_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (396, 152, 'Liuyue North_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (397, 152, 'Liuyue North_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (398, 152, 'Liuyue North_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (399, 152, 'Liuyue North_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (400, 152, 'Liuyue North_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (401, 153, 'Zhuzilin_B1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (402, 153, 'Zhuzilin_B2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (403, 153, 'Zhuzilin_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (404, 154, 'Fuyong_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (405, 155, 'Fumin_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (406, 155, 'Fumin_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (407, 155, 'Fumin_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (408, 155, 'Fumin_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (409, 155, 'Fumin_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (410, 155, 'Fumin_J1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (411, 155, 'Fumin_J3出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (412, 155, 'Fumin_K出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (413, 156, 'Shenzhen University_A2、A3出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (414, 156, 'Shenzhen University_A4出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (415, 156, 'Shenzhen University_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (416, 157, 'Universiade_2号出入口/10号出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (417, 157, 'Universiade_3号出入口/13号出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (418, 157, 'Universiade_11号出入口/12号出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (419, 158, 'Taiziwan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (420, 158, 'Taiziwan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (421, 159, 'Gangxia_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (422, 159, 'Gangxia_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (423, 159, 'Gangxia_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (424, 159, 'Gangxia_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (425, 159, 'Gangxia_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (426, 159, 'Gangxia_G出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (427, 160, 'Xiangmi_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (428, 160, 'Xiangmi_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (429, 161, 'Ailian_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (430, 161, 'Ailian_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (431, 162, 'Bao\'an Center_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (432, 162, 'Bao\'an Center_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (433, 162, 'Bao\'an Center_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (434, 163, 'Chegongmiao_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (435, 163, 'Chegongmiao_J1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (436, 164, 'Qiaoxiang_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (437, 164, 'Qiaoxiang_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (438, 164, 'Qiaoxiang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (439, 165, 'Lianhuacun _A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (440, 165, 'Lianhuacun _C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (441, 166, 'Cuizhu_B2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (442, 166, 'Cuizhu_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (443, 167, 'Changhu_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (444, 168, 'Baohua_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (445, 168, 'Baohua_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (446, 168, 'Baohua_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (447, 168, 'Baohua_B2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (448, 169, 'Wuhe_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (449, 169, 'Wuhe_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (450, 169, 'Wuhe_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (451, 169, 'Wuhe_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (452, 169, 'Wuhe_D1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (453, 170, 'Convention & Exhibition Center_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (454, 171, 'Longjing_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (455, 171, 'Longjing_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (456, 172, 'Wenjin_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (457, 172, 'Wenjin_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (458, 172, 'Wenjin_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (459, 172, 'Wenjin_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (460, 173, 'Baolongtongle Station_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (461, 174, 'SIAT_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (462, 175, 'Liwan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (463, 175, 'Liwan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (464, 176, 'Lingzhi_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (465, 176, 'Lingzhi_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (466, 176, 'Lingzhi_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (467, 176, 'Lingzhi_C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (468, 176, 'Lingzhi_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (469, 176, 'Lingzhi_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (470, 177, 'Xuexiang_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (471, 178, 'ShaTian_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (472, 178, 'ShaTian_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (473, 178, 'ShaTian_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (474, 178, 'ShaTian_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (475, 179, 'Shuiwan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (476, 179, 'Shuiwan_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (477, 180, 'Taoyuancun_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (478, 180, 'Taoyuancun_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (479, 180, 'Taoyuancun_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (480, 180, 'Taoyuancun_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (481, 181, 'Henggang_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (482, 182, 'Hongshan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (483, 183, 'Nanshan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (484, 183, 'Nanshan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (485, 183, 'Nanshan_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (486, 183, 'Nanshan_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (487, 183, 'Nanshan_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (488, 183, 'Nanshan_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (489, 183, 'Nanshan_G出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (490, 183, 'Nanshan_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (491, 184, 'Civic Center_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (492, 185, 'Railway Park_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (493, 186, 'Huaguoshan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (494, 186, 'Huaguoshan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (495, 186, 'Huaguoshan_C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (496, 186, 'Huaguoshan_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (497, 187, 'Shabo _A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (498, 188, 'Hubei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (499, 188, 'Hubei_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (500, 189, 'Shenzhen World_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (501, 189, 'Shenzhen World_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (502, 190, 'Mugu_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (503, 190, 'Mugu_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (504, 190, 'Mugu_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (505, 191, 'Lianhua North_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (506, 192, 'Changlingpi_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (507, 192, 'Changlingpi_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (508, 193, 'Sports Center_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (509, 193, 'Sports Center_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (510, 194, 'Hongshuwan South_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (511, 194, 'Hongshuwan South_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (512, 194, 'Hongshuwan South_E2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (513, 194, 'Hongshuwan South_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (514, 194, 'Hongshuwan South_东3出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (515, 194, 'Hongshuwan South_东1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (516, 194, 'Hongshuwan South_西广场出口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (517, 195, 'Dafen_');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (518, 196, 'Nanyou_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (519, 196, 'Nanyou_F1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (520, 196, 'Nanyou_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (521, 196, 'Nanyou_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (522, 197, 'Tongle South_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (523, 198, 'Zhongwu South_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (524, 199, 'Pingshan Station_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (525, 199, 'Pingshan Station_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (526, 200, 'Shenkang_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (527, 201, 'Shangsha_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (528, 201, 'Shangsha_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (529, 201, 'Shangsha_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (530, 202, 'Xiasha_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (531, 202, 'Xiasha_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (532, 202, 'Xiasha_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (533, 203, 'Sihai_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (534, 204, 'Waterlands Resort South_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (535, 205, 'Zhenmei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (536, 205, 'Zhenmei_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (537, 206, 'Houhai_G出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (538, 206, 'Houhai_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (539, 207, 'Wutong Mountain South_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (540, 208, 'Maling_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (541, 208, 'Maling_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (542, 208, 'Maling_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (543, 209, 'Tangwei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (544, 209, 'Tangwei_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (545, 209, 'Tangwei_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (546, 209, 'Tangwei_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (547, 210, ' Shengping Station_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (548, 210, ' Shengping Station_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (549, 211, 'University of technology_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (550, 211, 'University of technology_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (551, 211, 'University of technology_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (552, 212, 'Airport East_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (553, 212, 'Airport East_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (554, 213, 'Tangkeng_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (555, 214, 'Longcheng Square_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (556, 214, 'Longcheng Square_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (557, 214, 'Longcheng Square_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (558, 215, 'Mission Hills_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (559, 216, 'Xiashuijing_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (560, 216, 'Xiashuijing_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (561, 217, 'Huangtian_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (562, 217, 'Huangtian_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (563, 218, 'Xinhe Station_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (564, 218, 'Xinhe Station_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (565, 218, 'Xinhe Station_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (566, 219, 'Baishizhou_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (567, 219, 'Baishizhou_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (568, 219, 'Baishizhou_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (569, 219, 'Baishizhou_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (570, 220, 'Window of the World_');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (571, 221, 'Huangbeiling_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (572, 221, 'Huangbeiling_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (573, 221, 'Huangbeiling_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (574, 221, 'Huangbeiling_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (575, 222, 'Baigelong_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (576, 222, 'Baigelong_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (577, 223, 'Dameisha_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (578, 223, 'Dameisha_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (579, 224, 'Nantou Ancient City_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (580, 225, 'Pingshan Square _A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (581, 225, 'Pingshan Square _C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (582, 225, 'Pingshan Square _C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (583, 225, 'Pingshan Square _D1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (584, 225, 'Pingshan Square _D2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (585, 225, 'Pingshan Square _E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (586, 226, 'Qiaocheng East_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (587, 226, 'Qiaocheng East_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (588, 226, 'Qiaocheng East_C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (589, 227, 'Meilinguan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (590, 227, 'Meilinguan_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (591, 228, 'Longdong Station_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (592, 228, 'Longdong Station_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (593, 228, 'Longdong Station_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (594, 229, 'Science Museum_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (595, 229, 'Science Museum_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (596, 229, 'Science Museum_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (597, 229, 'Science Museum_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (598, 230, 'Hongling North_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (599, 230, 'Hongling North_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (600, 230, 'Hongling North_J出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (601, 231, 'Yihai_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (602, 232, 'Zuopaotai East_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (603, 233, 'Shijing_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (604, 233, 'Shijing_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (605, 233, 'Shijing_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (606, 234, 'Hongling_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (607, 234, 'Hongling_C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (608, 234, 'Hongling_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (609, 234, 'Hongling_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (610, 234, 'Hongling_G出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (611, 234, 'Hongling_H出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (612, 235, 'University Town_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (613, 235, 'University Town_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (614, 235, 'University Town_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (615, 236, 'Shatoujiao_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (616, 236, 'Shatoujiao_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (617, 236, 'Shatoujiao_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (618, 237, 'Linhai_B2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (619, 238, 'Bagualing_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (620, 238, 'Bagualing_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (621, 238, 'Bagualing_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (622, 238, 'Bagualing_G2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (623, 239, 'Guangming_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (624, 240, 'Shenzhen Bay Park_D1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (625, 240, 'Shenzhen Bay Park_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (626, 240, 'Shenzhen Bay Park_D2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (627, 241, 'Houting_A、B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (628, 241, 'Houting_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (629, 242, 'Shangmeilin_G出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (630, 242, 'Shangmeilin_J1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (631, 243, 'Honglang North_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (632, 243, 'Honglang North_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (633, 243, 'Honglang North_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (634, 243, 'Honglang North_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (635, 244, 'Gankeng_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (636, 244, 'Gankeng_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (637, 245, 'Qinghu_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (638, 246, 'He\'ao_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (639, 246, 'He\'ao_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (640, 246, 'He\'ao_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (641, 246, 'He\'ao_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (642, 247, 'Nanlian_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (643, 247, 'Nanlian_B1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (644, 247, 'Nanlian_B2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (645, 248, 'Yuanling_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (646, 248, 'Yuanling_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (647, 249, 'Xin\'an Park_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (648, 249, 'Xin\'an Park_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (649, 250, 'Shenzhen World South_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (650, 251, 'Liantang_');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (651, 252, 'Yonghu_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (652, 252, 'Yonghu_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (653, 253, 'Baishilong_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (654, 254, 'Buji_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (655, 254, 'Buji_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (656, 254, 'Buji_E2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (657, 254, 'Buji_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (658, 254, 'Buji_东3出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (659, 254, 'Buji_东1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (660, 254, 'Buji_西广场出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (661, 255, 'Liuxiandong_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (662, 255, 'Liuxiandong_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (663, 256, 'Fenghuang Town_A/B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (664, 256, 'Fenghuang Town_C/D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (665, 257, 'Xitou_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (666, 257, 'Xitou_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (667, 258, 'Shanglilang_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (668, 258, 'Shanglilang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (669, 259, 'Longsheng_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (670, 260, 'Huanggang Checkpoint_D/E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (671, 261, 'Honghu_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (672, 261, 'Honghu_C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (673, 261, 'Honghu_');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (674, 261, 'Honghu_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (675, 261, 'Honghu_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (676, 261, 'Honghu_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (677, 262, 'Renmin South_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (678, 262, 'Renmin South_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (679, 262, 'Renmin South_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (680, 262, 'Renmin South_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (681, 263, 'Guiwan_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (682, 264, 'Guangming St_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (683, 264, 'Guangming St_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (684, 264, 'Guangming St_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (685, 264, 'Guangming St_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (686, 265, 'Yantian Rd_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (687, 265, 'Yantian Rd_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (688, 265, 'Yantian Rd_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (689, 266, 'Honganwei_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (690, 266, 'Honganwei_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (691, 266, 'Honganwei_B2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (692, 266, 'Honganwei_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (693, 267, 'Zhongshan Park_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (694, 267, 'Zhongshan Park_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (695, 267, 'Zhongshan Park_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (696, 267, 'Zhongshan Park_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (697, 268, 'Nanyue_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (698, 268, 'Nanyue_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (699, 268, 'Nanyue_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (700, 268, 'Nanyue_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (701, 269, 'Shangshuijing_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (702, 270, 'Huaqiang South_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (703, 270, 'Huaqiang South_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (704, 271, 'Xiangmihu_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (705, 271, 'Xiangmihu_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (706, 272, 'Xiangmei_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (707, 272, 'Xiangmei_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (708, 272, 'Xiangmei_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (709, 272, 'Xiangmei_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (710, 273, 'Xiameilin_B1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (711, 273, 'Xiameilin_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (712, 274, 'Shuangyong St_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (713, 274, 'Shuangyong St_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (714, 274, 'Shuangyong St_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (715, 275, 'Waterlands Resort East_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (716, 276, 'Zhangbei_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (717, 276, 'Zhangbei_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (718, 277, 'Qianwan Park_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (719, 278, 'Qianhaiwan_1.A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (720, 279, 'Keyuan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (721, 280, 'Jingtian_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (722, 280, 'Jingtian_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (723, 280, 'Jingtian_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (724, 280, 'Jingtian_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (725, 280, 'Jingtian_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (726, 280, 'Jingtian_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (727, 281, 'Xinxiu_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (728, 281, 'Xinxiu_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (729, 282, 'Shenzhen North Station_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (730, 282, 'Shenzhen North Station_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (731, 283, 'Longhua_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (732, 284, 'Airport_B出入口/C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (733, 285, 'Grand Theater_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (734, 285, 'Grand Theater_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (735, 285, 'Grand Theater_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (736, 286, 'Xingwei_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (737, 286, 'Xingwei_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (738, 287, 'Fuwei_此站暂无数据');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (739, 288, 'Huanggekeng  station_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (740, 288, 'Huanggekeng  station_A2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (741, 288, 'Huanggekeng  station_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (742, 288, 'Huanggekeng  station_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (743, 288, 'Huanggekeng  station_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (744, 289, 'Bao\'an Passenger Transport Terminal_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (745, 289, 'Bao\'an Passenger Transport Terminal_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (746, 289, 'Bao\'an Passenger Transport Terminal_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (747, 290, 'Qiaocheng North_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (748, 290, 'Qiaocheng North_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (749, 290, 'Qiaocheng North_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (750, 291, 'Tongxinling_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (751, 291, 'Tongxinling_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (752, 291, 'Tongxinling_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (753, 291, 'Tongxinling_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (754, 291, 'Tongxinling_E1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (755, 291, 'Tongxinling_E2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (756, 291, 'Tongxinling_F出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (757, 292, 'Nanyou West_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (758, 292, 'Nanyou West_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (759, 292, 'Nanyou West_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (760, 293, 'Hongshuwan_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (761, 293, 'Hongshuwan_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (762, 294, 'Yantian Port West_A1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (763, 294, 'Yantian Port West_B2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (764, 294, 'Yantian Port West_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (765, 295, 'Meicun_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (766, 295, 'Meicun_C1出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (767, 295, 'Meicun_C2出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (768, 295, 'Meicun_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (769, 295, 'Meicun_E出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (770, 296, 'Changzhen_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (771, 296, 'Changzhen_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (772, 296, 'Changzhen_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (773, 296, 'Changzhen_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (774, 297, 'Baolong_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (775, 297, 'Baolong_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (776, 297, 'Baolong_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (777, 298, 'Chiwan_C、B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (778, 299, 'Sun Yat-sen University_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (779, 300, 'Xili Lake_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (780, 300, 'Xili Lake_D出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (781, 301, 'Liutang_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (782, 301, 'Liutang_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (783, 302, 'Yuyuan  station_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (784, 302, 'Yuyuan  station_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (785, 302, 'Yuyuan  station_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (786, 303, 'Tianxin_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (787, 303, 'Tianxin_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (788, 304, 'Daxin_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (789, 305, 'Hehua_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (790, 305, 'Hehua_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (791, 305, 'Hehua_C出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (792, 306, 'Yijing_A出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (793, 306, 'Yijing_B出入口');
INSERT INTO project2.chukous (chukou_id, station_id, chukou_name) VALUES (794, 306, 'Yijing_D出入口');
