create table line_stations
(
    line_station_id int auto_increment
        primary key,
    line_id         int          not null,
    station_name    varchar(255) not null,
    station_order   int          null,
    constraint line_id
        unique (line_id, station_name),
    constraint line_stations_ibfk_1
        foreign key (line_id) references `lines` (line_id),
    constraint line_stations_ibfk_2
        foreign key (station_name) references stations (english_name)
);

create index station_name
    on line_stations (station_name);

INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (1, 1, 'Futian Checkpoint', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (2, 1, 'Fumin', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (3, 1, 'Convention & Exhibition Center', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (4, 1, 'Civic Center', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (5, 1, 'Children\'s Palace', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (6, 1, 'Lianhua North', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (7, 1, 'Shangmeilin', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (8, 1, 'Minle', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (9, 1, 'Baishilong', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (10, 1, 'Shenzhen North Station', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (11, 1, 'Hongshan', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (12, 1, 'Shangtang', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (13, 1, 'Longsheng', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (14, 1, 'Longhua', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (15, 1, 'Qinghu', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (16, 1, 'Qinghu North', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (17, 1, 'Zhucun', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (18, 1, 'Xikeng', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (19, 1, 'Changhu', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (20, 1, 'Guanlan', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (21, 1, 'Songyuanxia', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (22, 1, 'Mission Hills', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (23, 1, 'Niuhu', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (24, 2, 'Qianwan', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (25, 2, 'Menghai', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (26, 2, 'Yihai', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (27, 2, 'Litchi Orchards', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (28, 2, 'Nanyou West', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (29, 2, 'Nanyou', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (30, 2, 'Nanshan Book Mall', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (31, 2, 'Shenzhen University South', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (32, 2, 'Yuehaimen', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (33, 2, 'Hi-tech South', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (34, 2, 'Hongshuwan South', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (35, 2, 'Shenwan', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (36, 2, 'Shenzhen Bay Park', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (37, 2, 'Xiasha', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (38, 2, 'Chegongmiao', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (39, 2, 'Xiangmei', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (40, 2, 'Jingtian', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (41, 2, 'Meijing', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (42, 2, 'Xiameilin', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (43, 2, 'Meicun', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (44, 2, 'Shangmeilin', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (45, 2, 'Maling', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (46, 2, 'Yinhu', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (47, 2, 'Nigang', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (48, 2, 'Hongling North', 25);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (49, 2, 'Yuanling', 26);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (50, 2, 'Hongling', 27);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (51, 2, 'Hongling South', 28);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (52, 2, 'Ludancun', 29);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (53, 2, 'Renmin South', 30);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (54, 2, 'Xiangxicun', 31);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (55, 2, 'Wenjin', 32);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (56, 3, 'Guangming', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (57, 3, 'Zhenmei', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (58, 3, 'Sun Yat-sen University', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (59, 3, 'SIAT', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (60, 4, 'Xili Lake', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (61, 4, 'Xili', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (62, 4, 'Chaguang', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (63, 4, 'Zhuguang', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (64, 4, 'Longjing', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (65, 4, 'Taoyuancun', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (66, 4, 'Shenyun', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (67, 4, 'Antuo Hill', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (68, 4, 'Nonglin', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (69, 4, 'Chegongmiao', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (70, 4, 'Shangsha', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (71, 4, 'Shawei', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (72, 4, 'Shixia', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (73, 4, 'Huanggangcun', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (74, 4, 'Fumin', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (75, 4, 'Huanggang Checkpoint', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (76, 4, 'Chiwei', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (77, 4, 'Huaqiang South', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (78, 4, 'Huaqiang North', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (79, 4, 'Huaxin', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (80, 4, 'Huangmugang', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (81, 4, 'Bagualing', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (82, 4, 'Hongling North', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (83, 4, 'Sungang', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (84, 4, 'Honghu', 25);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (85, 4, 'Tianbei', 26);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (86, 4, 'Tai\'an', 27);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (87, 5, 'Gangxia North', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (88, 5, 'Futian', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (89, 5, 'Chegongmiao', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (90, 5, 'Hongshuwan South', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (91, 5, 'Houhai', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (92, 5, 'Nanshan', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (93, 5, 'Qianhaiwan', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (94, 5, 'Bao\'an', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (95, 5, 'Bihaiwan', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (96, 5, 'Airport', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (97, 5, 'Airport North', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (98, 5, 'Fuyong', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (99, 5, 'Qiaotou', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (100, 5, 'Tangwei', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (101, 5, 'Ma\'an Hill', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (102, 5, 'Shajing', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (103, 5, 'Houting', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (104, 5, 'Songgang', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (105, 5, 'Bitou', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (106, 6, 'Gangxia North', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (107, 6, 'Huangmugang', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (108, 6, 'Luohu  North', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (109, 6, 'Buji', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (110, 6, 'Shiyaling', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (111, 6, 'Liuyue North', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (112, 6, 'Silian', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (113, 6, 'Aobei', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (114, 6, 'Universiade', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (115, 6, 'Zhangbei', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (116, 6, 'Nanyue', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (117, 6, 'Baolong', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (118, 6, 'Jinlong', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (119, 6, 'Pingshan wei', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (120, 6, 'Pingshan Square ', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (121, 6, 'Pingshan Center', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (122, 6, 'Kengzi', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (123, 6, 'ShaTian', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (124, 7, 'Chiwan', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (125, 7, 'Shekou Port', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (126, 7, 'Sea World', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (127, 7, 'Shuiwan', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (128, 7, 'Dongjiaotou', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (129, 7, 'Wanxia', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (130, 7, 'Haiyue', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (131, 7, 'Dengliang', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (132, 7, 'Houhai', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (133, 7, 'Keyuan', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (134, 7, 'Hongshuwan', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (135, 7, 'Window of the World', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (136, 7, 'Qiaocheng North', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (137, 7, 'Shenkang', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (138, 7, 'Antuo Hill', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (139, 7, 'Qiaoxiang', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (140, 7, 'Xiangmi', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (141, 7, 'Xiangmei North', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (142, 7, 'Jingtian', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (143, 7, 'Lianhua West', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (144, 7, 'Futian', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (145, 7, 'Civic Center', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (146, 7, 'Gangxia North', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (147, 7, 'Huaqiang North', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (148, 7, 'Yannan', 25);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (149, 7, 'Grand Theater', 26);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (150, 7, 'Hubei', 27);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (151, 7, 'Huangbeiling', 28);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (152, 7, 'Xinxiu', 29);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (153, 7, 'Liantang Checkpoint', 30);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (154, 7, 'Xianhu Rd', 31);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (155, 7, 'Liantang', 32);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (156, 8, 'Futian Bonded Area', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (157, 8, 'Yitian', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (158, 8, 'Shixia', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (159, 8, 'Shopping Park', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (160, 8, 'Futian', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (161, 8, 'Children\'s Palace', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (162, 8, 'Lianhuacun ', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (163, 8, 'Huaxin', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (164, 8, 'Tongxinling', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (165, 8, 'Hongling', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (166, 8, 'Laojie', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (167, 8, 'Shaibu', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (168, 8, 'Cuizhu', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (169, 8, 'Tianbei', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (170, 8, 'Shuibei', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (171, 8, 'Caopu', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (172, 8, 'Buji', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (173, 8, 'Mumianwan', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (174, 8, 'Dafen', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (175, 8, 'Danzhutou', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (176, 8, 'Liuyue', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (177, 8, 'Tangkeng', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (178, 8, 'Henggang', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (179, 8, 'Yonghu', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (180, 8, 'He\'ao', 25);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (181, 8, 'Universiade', 26);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (182, 8, 'Ailian', 27);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (183, 8, 'Jixiang', 28);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (184, 8, 'Longcheng Square', 29);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (185, 8, 'Nanlian', 30);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (186, 8, 'Shuanglong Station', 31);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (187, 9, 'Wutong Mountain South', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (188, 9, 'Shatoujiao', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (189, 9, 'Haishan', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (190, 9, 'Yantian Port West', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (191, 9, 'Shenwai Senior Campus', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (192, 9, 'Yantian Rd', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (193, 9, 'Honganwei', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (194, 9, 'Yantianxu', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (195, 9, 'Dameisha', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (196, 9, 'Xiaomeisha', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (197, 10, 'Futian Checkpoint', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (198, 10, 'Fumin', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (199, 10, 'Gangxia', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (200, 10, 'Gangxia North', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (201, 10, 'Lianhuacun ', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (202, 10, 'Donggualing', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (203, 10, 'Maling', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (204, 10, 'Yabao', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (205, 10, 'Nankeng', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (206, 10, 'Guangyayuan', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (207, 10, 'Wuhe', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (208, 10, 'Bantian North', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (209, 10, 'Bei\'er Rd', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (210, 10, 'Huawei', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (211, 10, 'Gangtou', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (212, 10, 'Xuexiang', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (213, 10, 'Gankeng', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (214, 10, 'Liangmao Hill', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (215, 10, 'Shanglilang', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (216, 10, 'Mugu', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (217, 10, 'Huanancheng', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (218, 10, 'Hehua', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (219, 10, 'Pinghu', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (220, 10, 'Shuangyong St', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (221, 11, 'Universiade', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (222, 11, 'Universiade Center', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (223, 11, '  Longcheng Park', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (224, 11, 'Huanggekeng  station', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (225, 11, 'Yuyuan  station', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (226, 11, 'Huilongpu  station
', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (227, 11, 'Shangjing Station', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (228, 11, ' Shengping Station', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (229, 11, 'Longyuan Station', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (230, 11, 'Shuanglong Station', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (231, 11, 'Xintangwei Station', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (232, 11, 'Longdong Station', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (233, 11, 'Baolongtongle Station', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (234, 11, 'Pingshan Station', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (235, 11, 'Xinhe Station', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (236, 11, 'Liuhe station', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (237, 11, 'Pingshan wei', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (238, 11, 'Pinghuan', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (239, 11, 'Dongjiang Column Memorial 
Hall Station', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (240, 11, 'Shabo ', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (241, 11, 'Yanzihu', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (242, 11, 'Shijing', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (243, 11, 'University of technology', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (244, 11, 'Tianxin', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (245, 12, 'Luohu', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (246, 12, 'Guomao', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (247, 12, 'Laojie', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (248, 12, 'Grand Theater', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (249, 12, 'Science Museum', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (250, 12, 'Huaqiang Rd', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (251, 12, 'Gangxia', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (252, 12, 'Convention & Exhibition Center', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (253, 12, 'Shopping Park', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (254, 12, 'Xiangmihu', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (255, 12, 'Chegongmiao', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (256, 12, 'Zhuzilin', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (257, 12, 'Qiaocheng East', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (258, 12, 'OCT', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (259, 12, 'Window of the World', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (260, 12, 'Baishizhou', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (261, 12, 'Hi-Tech Park', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (262, 12, 'Shenzhen University', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (263, 12, 'Taoyuan', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (264, 12, 'Daxin', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (265, 12, 'Liyumen', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (266, 12, 'Qianhaiwan', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (267, 12, 'Xin\'an', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (268, 12, 'Bao\'an Center', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (269, 12, 'Bao\'an Stadium', 25);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (270, 12, 'Pingzhou', 26);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (271, 12, 'Xixiang', 27);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (272, 12, 'Gushu', 28);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (273, 12, 'Hourui', 29);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (274, 12, 'Airport East', 30);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (275, 13, 'Science Museum', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (276, 13, 'Tongxinling', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (277, 13, 'Sports Center', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (278, 13, 'Bagualing', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (279, 13, 'Yinhu', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (280, 13, 'Hanling', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (281, 13, 'Meilinguan', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (282, 13, 'Shenzhen North Station', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (283, 13, 'Hongshan', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (284, 13, 'Shangfen', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (285, 13, 'Yuanfen', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (286, 13, 'Yangtai Mountain East', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (287, 13, 'Guantian', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (288, 13, 'Shangwu', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (289, 13, 'Changzhen', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (290, 13, 'Fenghuang Town', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (291, 13, 'Guangming St', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (292, 13, 'Guangming', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (293, 13, 'Science Park', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (294, 13, 'Loucun', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (295, 13, 'Honghuashan', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (296, 13, 'Gongming Square', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (297, 13, 'Heshuikou', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (298, 13, 'Shutianpu', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (299, 13, 'Songgang Park', 25);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (300, 13, 'Xitou', 26);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (301, 13, 'Songgang', 27);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (302, 14, 'Airport North', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (303, 14, 'Shenzhen World South', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (304, 14, 'Shenzhen World', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (305, 14, 'Shenzhen World North', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (306, 14, 'Convention & Exhibition City', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (307, 15, 'Chiwan', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (308, 15, 'Liwan', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (309, 15, 'Railway Park', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (310, 15, 'Mawan', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (311, 15, 'Qianwan Park', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (312, 15, 'Qianwan', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (313, 15, 'Guiwan', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (314, 15, 'Qianhaiwan', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (315, 15, 'Linhai', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (316, 15, 'Baohua', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (317, 15, 'Bao\'an Center', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (318, 15, 'Fanshen', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (319, 15, 'Lingzhi', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (320, 15, 'Honglang North', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (321, 15, 'Xingdong', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (322, 15, 'Liuxiandong', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (323, 15, 'Xili', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (324, 15, 'University Town', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (325, 15, 'Tanglang', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (326, 15, 'Changlingpi', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (327, 15, 'Shenzhen North Station', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (328, 15, 'Minzhi', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (329, 15, 'Wuhe', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (330, 15, 'Bantian', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (331, 15, 'Yangmei', 25);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (332, 15, 'Shangshuijing', 26);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (333, 15, 'Xiashuijing', 27);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (334, 15, 'Changlong', 28);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (335, 15, 'Buji', 29);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (336, 15, 'Baigelong', 30);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (337, 15, 'Buxin', 31);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (338, 15, 'Tai\'an', 32);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (339, 15, 'Yijing', 33);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (340, 15, 'Huangbeiling', 34);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (341, 16, 'Zuopaotai East', 1);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (342, 16, 'Taiziwan', 2);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (343, 16, 'Sea World', 3);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (344, 16, 'Huaguoshan', 4);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (345, 16, 'Sihai', 5);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (346, 16, 'Nanyou', 6);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (347, 16, 'Nanguang', 7);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (348, 16, 'Nanshan', 8);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (349, 16, 'Taoyuan', 9);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (350, 16, 'Nantou Ancient City', 10);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (351, 16, 'Zhongshan Park', 11);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (352, 16, 'Tongle South', 12);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (353, 16, 'Xin\'an Park', 13);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (354, 16, 'Lingzhi', 14);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (355, 16, 'Shangchuan', 15);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (356, 16, 'Liutang', 16);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (357, 16, 'Bao\'an Passenger Transport Terminal', 17);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (358, 16, 'Baotian 1st Road', 18);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (359, 16, 'Pingluan Hill', 19);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (360, 16, 'Xixiang Taoyuan', 20);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (361, 16, 'Zhongwu South', 21);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (362, 16, 'Huangtian', 22);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (363, 16, 'Xingwei', 23);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (364, 16, 'Airport East', 24);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (365, 16, 'Fuwei', 25);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (366, 16, 'Huaide', 26);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (367, 16, 'Fuyong', 27);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (368, 16, 'Qiaotou West', 28);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (369, 16, 'Fuhai West', 29);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (370, 16, 'Shenzhen World', 30);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (371, 16, 'Shenzhen World North', 31);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (372, 16, 'Waterlands Resort South', 32);
INSERT INTO project2.line_stations (line_station_id, line_id, station_name, station_order) VALUES (373, 16, 'Waterlands Resort East', 33);
